const cron = require('node-cron');
const tmdbService = require('../services/tmdbService');
const db = require('../config/db');
const redis = require('../config/redis');

class SyncMoviesJob {
    start() {
        // Test amaçlı olarak her 10 dakikada bir çalışacak şekilde ayarlandı.
        // Gerçek senaryoda her gece saat 03:00 için: '0 3 * * *' kullanılır.
        cron.schedule('*/10 * * * *', async () => {
            console.log(`[CRON] ${new Date().toISOString()} - Film senkronizasyonu başlatılıyor...`);
            await this.syncMovies();
        });

        // Sunucu ayağa kalkar kalkmaz 1 kere anında senkronize edelim (Test için çok faydalıdır)
        console.log('[CRON] Sunucu başlangıcı için ilk senkronizasyon tetiklendi.');
        this.syncMovies();
    }

    async syncMovies() {
        try {
            // Sinema isimlerini güncelle: Paribu -> SBRS
            await db.query("UPDATE cinemas SET name = REPLACE(name, 'Paribu', 'SBRS') WHERE name LIKE '%Paribu%'");
            console.log("[CRON] Sinema isimleri güncellendi (Paribu -> SBRS).");

            const nowPlaying = await tmdbService.getNowPlayingMovies();
            const upcoming = await tmdbService.getUpcomingMovies();
            const movies = [...nowPlaying, ...upcoming];
            
            // Deduplicate movies by title
            const uniqueMovies = [];
            const seenTitles = new Set();
            for (const movie of movies) {
                const cleanTitle = movie.title.trim();
                if (!seenTitles.has(cleanTitle)) {
                    seenTitles.add(cleanTitle);
                    uniqueMovies.push(movie);
                }
            }

            let addedCount = 0;
            let autoGeneratedCount = 0;

            for (const movie of uniqueMovies) {
                const upsertQuery = `
                    INSERT INTO movies (title, description, duration_minutes, release_date, poster_url)
                    VALUES ($1, $2, $3, $4, $5)
                    ON CONFLICT (title) DO UPDATE 
                    SET description = EXCLUDED.description,
                        duration_minutes = EXCLUDED.duration_minutes,
                        release_date = EXCLUDED.release_date,
                        poster_url = EXCLUDED.poster_url
                    WHERE movies.description IS DISTINCT FROM EXCLUDED.description
                       OR movies.duration_minutes IS DISTINCT FROM EXCLUDED.duration_minutes
                       OR movies.release_date IS DISTINCT FROM EXCLUDED.release_date
                       OR movies.poster_url IS DISTINCT FROM EXCLUDED.poster_url
                    RETURNING (xmax = 0) AS is_inserted
                `;
                const res = await db.query(upsertQuery, [
                    movie.title.trim(), 
                    movie.description, 
                    movie.durationMinutes, 
                    movie.releaseDate, 
                    movie.posterUrl
                ]);
                
                if (res.rows.length > 0 && res.rows[0].is_inserted) {
                    addedCount++;
                }

                // Get movie details to check for sessions
                const dbMovieRes = await db.query('SELECT id, release_date, duration_minutes FROM movies WHERE title = $1', [movie.title.trim()]);
                if (dbMovieRes.rows.length > 0) {
                    const dbMovie = dbMovieRes.rows[0];
                    const releaseDateObj = new Date(dbMovie.release_date);
                    const today = new Date();
                    today.setHours(0, 0, 0, 0);

                    // Only generate sessions if movie is currently playing (release_date <= today)
                    if (releaseDateObj <= today) {
                        const countRes = await db.query('SELECT COUNT(*) FROM showtimes WHERE movie_id = $1', [dbMovie.id]);
                        const showtimeCount = parseInt(countRes.rows[0].count);

                        if (showtimeCount === 0) {
                            console.log(`[CRON] ${movie.title.trim()} için hiç seans bulunamadı. Otomatik seanslar oluşturuluyor...`);
                            await this.generateShowtimesForMovie(dbMovie.id, dbMovie.duration_minutes || 120);
                            autoGeneratedCount++;
                        }
                    }
                }
            }

            // Clear showtimes of movies that are not in the current TMDB list
            if (uniqueMovies.length > 0) {
                const currentMovieTitles = uniqueMovies.map(m => m.title.trim());
                const deleteShowtimesQuery = `
                    DELETE FROM showtimes 
                    WHERE movie_id IN (
                        SELECT id FROM movies WHERE title NOT IN (SELECT unnest($1::varchar[]))
                    )
                `;
                const deleteRes = await db.query(deleteShowtimesQuery, [currentMovieTitles]);
                if (deleteRes.rowCount > 0) {
                    console.log(`[CRON] Listeden kalkan filmlerin ${deleteRes.rowCount} adet seansı temizlendi.`);
                }
            }

            console.log(`[CRON] Senkronizasyon tamamlandı! Toplam işlenen film: ${movies.length}, Eklenen yeni: ${addedCount}, Seans atanan: ${autoGeneratedCount}`);
            
            // Redis'teki eski film listesi ve detay önbelleklerini temizle
            await redis.connect();
            if (redis.isAvailable()) {
                const client = redis.getClient();
                const keys = await client.keys('catalog:*');
                if (keys && keys.length > 0) {
                    await client.del(keys);
                    console.log(`[CRON] Redis'teki ${keys.length} adet film kataloğu önbelleği temizlendi.`);
                }
            }
            
        } catch (error) {
            console.error('[CRON ERROR] Film senkronizasyonu sırasında hata oluştu:', error.message);
        }
    }

    async generateShowtimesForMovie(movieId, durationMinutes) {
        try {
            const hallsRes = await db.query('SELECT id, name FROM halls');
            const halls = hallsRes.rows;
            if (halls.length === 0) {
                console.warn('[CRON WARNING] Veritabanında salon bulunamadı. Seans oluşturulamıyor.');
                return;
            }

            const movieIds = [];
            const hallIds = [];
            const startTimes = [];
            const endTimes = [];
            const prices = [];
            const formats = [];
            const languageTypes = [];

            for (const hall of halls) {
                const hallName = hall.name.toLowerCase();
                let price = 120.00;
                if (hallName.includes('vip')) price = 250.00;
                if (hallName.includes('imax')) price = 180.00;
                if (hallName.includes('premium')) price = 200.00;
                if (hallName.includes('büyük') || hallName.includes('large')) price = 140.00;
                if (hallName.includes('compact') || hallName.includes('küçük')) price = 100.00;

                for (let day = 0; day < 5; day++) {
                    let hourIdx = 0;
                    for (const hour of [10, 14, 18, 21]) {
                        const startTime = new Date();
                        startTime.setDate(startTime.getDate() + day);
                        startTime.setHours(hour, 0, 0, 0);

                        const endTime = new Date(startTime);
                        endTime.setMinutes(endTime.getMinutes() + durationMinutes + 20);

                        // Format belirle
                        let format = '2D';
                        if (hallName.includes('imax')) {
                            format = 'IMAX';
                        } else if (hour === 18 && hourIdx % 2 === 0) {
                            format = '3D';
                        }

                        // Dil seçeneği belirle
                        let languageType = 'Türkçe Dublaj';
                        if (hour === 21 || (hour === 14 && hourIdx % 2 === 1)) {
                            languageType = 'Türkçe Altyazılı';
                        }

                        movieIds.push(movieId);
                        hallIds.push(hall.id);
                        startTimes.push(startTime);
                        endTimes.push(endTime);
                        prices.push(price);
                        formats.push(format);
                        languageTypes.push(languageType);
                        
                        hourIdx++;
                    }
                }
            }

            if (movieIds.length > 0) {
                await db.query(`
                    INSERT INTO showtimes (movie_id, hall_id, start_time, end_time, price, format, language_type)
                    SELECT * FROM unnest(
                        $1::uuid[], $2::uuid[], $3::timestamptz[], $4::timestamptz[], $5::numeric[], $6::varchar[], $7::varchar[]
                    )
                `, [movieIds, hallIds, startTimes, endTimes, prices, formats, languageTypes]);
            }
        } catch (error) {
            console.error('[CRON ERROR] Otomatik seans oluşturulurken hata:', error.message);
        }
    }
}

module.exports = new SyncMoviesJob();

