const cron = require('node-cron');
const tmdbService = require('../services/tmdbService');
const db = require('../config/db');
const redis = require('../config/redis');

class SyncMoviesJob {
    start() {
        // Test amaçlı olarak her 10 dakikada bir çalışacak şekilde ayarlandı.
        // Gerçek senaryoda her gece saat 03:00 için: '0 3 * * *' kullanılır.
        cron.schedule('*/10 * * * *', async () => {
            console.log(`[CRON] ${new Date().toISOString()} - Film senkronizasyonu başlatılıyor...`);
            await this.syncMovies();
        });

        // Sunucu ayağa kalkar kalkmaz 1 kere anında senkronize edelim (Test için çok faydalıdır)
        console.log('[CRON] Sunucu başlangıcı için ilk senkronizasyon tetiklendi.');
        this.syncMovies();
    }

    async syncMovies() {
        try {
            // Sinema isimlerini güncelle: Paribu -> SBRS
            await db.query("UPDATE cinemas SET name = REPLACE(name, 'Paribu', 'SBRS') WHERE name LIKE '%Paribu%'");
            console.log("[CRON] Sinema isimleri güncellendi (Paribu -> SBRS).");

            const nowPlaying = await tmdbService.getNowPlayingMovies();
            const upcoming = await tmdbService.getUpcomingMovies();
            const movies = [...nowPlaying, ...upcoming];
            
            // Deduplicate movies by title
            const uniqueMovies = [];
            const seenTitles = new Set();
            for (const movie of movies) {
                const cleanTitle = movie.title.trim();
                if (!seenTitles.has(cleanTitle)) {
                    seenTitles.add(cleanTitle);
                    uniqueMovies.push(movie);
                }
            }

            let addedCount = 0;
            let autoGeneratedCount = 0;

            for (const movie of uniqueMovies) {
                const upsertQuery = `
                    INSERT INTO movies (title, description, duration_minutes, release_date, poster_url)
                    VALUES ($1, $2, $3, $4, $5)
                    ON CONFLICT (title) DO UPDATE 
                    SET description = EXCLUDED.description,
                        duration_minutes = EXCLUDED.duration_minutes,
                        release_date = EXCLUDED.release_date,
                        poster_url = EXCLUDED.poster_url
                    WHERE movies.description IS DISTINCT FROM EXCLUDED.description
                       OR movies.duration_minutes IS DISTINCT FROM EXCLUDED.duration_minutes
                       OR movies.release_date IS DISTINCT FROM EXCLUDED.release_date
                       OR movies.poster_url IS DISTINCT FROM EXCLUDED.poster_url
                    RETURNING (xmax = 0) AS is_inserted
                `;
                const res = await db.query(upsertQuery, [
                    movie.title.trim(), 
                    movie.description, 
                    movie.durationMinutes, 
                    movie.releaseDate, 
                    movie.posterUrl
                ]);
                
                if (res.rows.length > 0 && res.rows[0].is_inserted) {
                    addedCount++;
                }

                // Get movie details to check for sessions
                const dbMovieRes = await db.query('SELECT id, release_date, duration_minutes FROM movies WHERE title = $1', [movie.title.trim()]);
                if (dbMovieRes.rows.length > 0) {
                    const dbMovie = dbMovieRes.rows[0];
                    const releaseDateObj = new Date(dbMovie.release_date);
                    const today = new Date();
                    today.setHours(0, 0, 0, 0);

                    // Only generate sessions if movie is currently playing (release_date <= today)
                    if (releaseDateObj <= today) {
                        const countRes = await db.query('SELECT COUNT(*) FROM showtimes WHERE movie_id = $1', [dbMovie.id]);
                        const showtimeCount = parseInt(countRes.rows[0].count);

                        if (showtimeCount === 0) {
                            console.log(`[CRON] ${movie.title.trim()} için hiç seans bulunamadı. Otomatik seanslar oluşturuluyor...`);
                            await this.generateShowtimesForMovie(dbMovie.id, dbMovie.duration_minutes || 120);
                            autoGeneratedCount++;
                        }
                    }
                }
            }

            // Clear showtimes of movies that are not in the current TMDB list
            if (uniqueMovies.length > 0) {
                const currentMovieTitles = uniqueMovies.map(m => m.title.trim());
                const deleteShowtimesQuery = `
                    DELETE FROM showtimes 
                    WHERE movie_id IN (
                        SELECT id FROM movies WHERE title NOT IN (SELECT unnest($1::varchar[]))
                    )
                    AND id NOT IN (
                        SELECT DISTINCT showtime_id FROM tickets
                    )
                `;
                const deleteRes = await db.query(deleteShowtimesQuery, [currentMovieTitles]);
                if (deleteRes.rowCount > 0) {
                    console.log(`[CRON] Listeden kalkan filmlerin bilet satılmamış ${deleteRes.rowCount} adet seansı temizlendi.`);
                }
            }

            console.log(`[CRON] Senkronizasyon tamamlandı! Toplam işlenen film: ${movies.length}, Eklenen yeni: ${addedCount}, Seans atanan: ${autoGeneratedCount}`);
            
            // Redis'teki eski film listesi ve detay önbelleklerini temizle
            await redis.connect();
            if (redis.isAvailable()) {
                const client = redis.getClient();
                const keys = await client.keys('catalog:*');
                if (keys && keys.length > 0) {
                    await client.del(keys);
                    console.log(`[CRON] Redis'teki ${keys.length} adet film kataloğu önbelleği temizlendi.`);
                }
            }
            
        } catch (error) {
            console.error('[CRON ERROR] Film senkronizasyonu sırasında hata oluştu:', error.message);
        }
    }

    async generateShowtimesForMovie(movieId, durationMinutes) {
        try {
            const hallsRes = await db.query('SELECT id, name FROM halls');
            const halls = hallsRes.rows;
            if (halls.length === 0) {
                console.warn('[CRON WARNING] Veritabanında salon bulunamadı. Seans oluşturulamıyor.');
                return;
            }

            const minDate = new Date();
            minDate.setHours(0, 0, 0, 0);
            const maxDate = new Date();
            maxDate.setDate(maxDate.getDate() + 5);
            maxDate.setHours(23, 59, 59, 999);

            // Fetch existing showtimes for the next 5 days
            const existingShowtimesRes = await db.query(
                `SELECT s.id, s.hall_id, s.start_time, s.end_time, s.movie_id,
                        (SELECT COUNT(*) FROM tickets t WHERE t.showtime_id = s.id) as ticket_count
                 FROM showtimes s
                 WHERE s.start_time >= $1 AND s.start_time <= $2`,
                [minDate, maxDate]
            );
            
            const existingShowtimes = existingShowtimesRes.rows.map(row => ({
                id: row.id,
                hall_id: row.hall_id,
                start_time: new Date(row.start_time),
                end_time: new Date(row.end_time),
                movie_id: row.movie_id,
                ticket_count: parseInt(row.ticket_count || 0)
            }));

            // Fetch total showtime counts per movie to assist in rebalancing
            const movieShowtimeCountsRes = await db.query(
                `SELECT movie_id, COUNT(*) as count FROM showtimes GROUP BY movie_id`
            );
            const movieShowtimeCounts = {};
            movieShowtimeCountsRes.rows.forEach(r => {
                movieShowtimeCounts[r.movie_id] = parseInt(r.count);
            });

            const movieIds = [];
            const hallIds = [];
            const startTimes = [];
            const endTimes = [];
            const prices = [];
            const formats = [];
            const languageTypes = [];

            let generatedCount = 0;
            const targetCount = 10; // Target 10 showtimes for this new movie across the 5 days

            for (const hall of halls) {
                if (generatedCount >= targetCount) break;

                const hallName = hall.name.toLowerCase();
                let price = 120.00;
                if (hallName.includes('vip')) price = 250.00;
                if (hallName.includes('imax')) price = 180.00;
                if (hallName.includes('premium')) price = 200.00;
                if (hallName.includes('büyük') || hallName.includes('large')) price = 140.00;
                if (hallName.includes('compact') || hallName.includes('küçük')) price = 100.00;

                for (let day = 0; day < 5; day++) {
                    if (generatedCount >= targetCount) break;

                    let hourIdx = 0;
                    for (const hour of [10, 14, 18, 21]) {
                        if (generatedCount >= targetCount) break;

                        const startTime = new Date();
                        startTime.setDate(startTime.getDate() + day);
                        startTime.setHours(hour, 0, 0, 0);

                        const endTime = new Date(startTime);
                        endTime.setMinutes(endTime.getMinutes() + durationMinutes + 20);

                        // Find overlapping showtimes
                        const overlapping = existingShowtimes.filter(st => {
                            if (st.hall_id !== hall.id) return false;
                            // Overlap if: NOT (endTime <= st.start_time OR startTime >= st.end_time)
                            return !(endTime <= st.start_time || startTime >= st.end_time);
                        });

                        if (overlapping.length === 0) {
                            // Slot is completely free!
                            // Format belirle
                            let format = '2D';
                            if (hallName.includes('imax')) {
                                format = 'IMAX';
                            } else if (hour === 18 && hourIdx % 2 === 0) {
                                format = '3D';
                            }

                            // Dil seçeneği belirle
                            let languageType = 'Türkçe Dublaj';
                            if (hour === 21 || (hour === 14 && hourIdx % 2 === 1)) {
                                languageType = 'Türkçe Altyazılı';
                            }

                            movieIds.push(movieId);
                            hallIds.push(hall.id);
                            startTimes.push(startTime);
                            endTimes.push(endTime);
                            prices.push(price);
                            formats.push(format);
                            languageTypes.push(languageType);

                            existingShowtimes.push({
                                id: null, // New showtime not yet saved to DB
                                hall_id: hall.id,
                                start_time: startTime,
                                end_time: endTime,
                                movie_id: movieId,
                                ticket_count: 0
                            });

                            generatedCount++;
                        } else {
                            // Slot is occupied. Check if we can rebalance by replacing it
                            // We can replace if ALL overlapping showtimes have 0 tickets and the other movie has > 10 showtimes
                            const canReplace = overlapping.every(st => {
                                const otherMovieCount = movieShowtimeCounts[st.movie_id] || 0;
                                return st.ticket_count === 0 && otherMovieCount > 10 && st.movie_id !== movieId;
                            });

                            if (canReplace) {
                                // Delete overlapping showtimes from DB and memory
                                for (const st of overlapping) {
                                    if (st.id) {
                                        await db.query('DELETE FROM showtimes WHERE id = $1', [st.id]);
                                        // Update counts
                                        movieShowtimeCounts[st.movie_id] = (movieShowtimeCounts[st.movie_id] || 1) - 1;
                                    }
                                    const index = existingShowtimes.indexOf(st);
                                    if (index > -1) {
                                        existingShowtimes.splice(index, 1);
                                    }
                                }

                                // Format belirle
                                let format = '2D';
                                if (hallName.includes('imax')) {
                                    format = 'IMAX';
                                } else if (hour === 18 && hourIdx % 2 === 0) {
                                    format = '3D';
                                }

                                // Dil seçeneği belirle
                                let languageType = 'Türkçe Dublaj';
                                if (hour === 21 || (hour === 14 && hourIdx % 2 === 1)) {
                                    languageType = 'Türkçe Altyazılı';
                                }

                                movieIds.push(movieId);
                                hallIds.push(hall.id);
                                startTimes.push(startTime);
                                endTimes.push(endTime);
                                prices.push(price);
                                formats.push(format);
                                languageTypes.push(languageType);

                                existingShowtimes.push({
                                    id: null,
                                    hall_id: hall.id,
                                    start_time: startTime,
                                    end_time: endTime,
                                    movie_id: movieId,
                                    ticket_count: 0
                                });

                                generatedCount++;
                            }
                        }

                        hourIdx++;
                    }
                }
            }

            if (movieIds.length > 0) {
                await db.query(`
                    INSERT INTO showtimes (movie_id, hall_id, start_time, end_time, price, format, language_type)
                    SELECT * FROM unnest(
                        $1::uuid[], $2::uuid[], $3::timestamptz[], $4::timestamptz[], $5::numeric[], $6::varchar[], $7::varchar[]
                    )
                `, [movieIds, hallIds, startTimes, endTimes, prices, formats, languageTypes]);
                console.log(`[CRON] ${movieIds.length} adet seans çakışmasız ve dengeli şekilde oluşturuldu.`);
            }
        } catch (error) {
            console.error('[CRON ERROR] Otomatik seans oluşturulurken hata:', error.message);
        }
    }
}

module.exports = new SyncMoviesJob();

